### ISSUE TITLE
Add support for OpenCart 3.0.3.9 and PHP 8

### ISSUE THREAD

**Issue by dennisbuijsgmailcom** [MultiSafepay/Opencart#14]
Hi

Please add support for 3.0.3.9 which is PHP compatible.
I am using it on 3.0.3.9 with PHP 8 and made some changes, see zip and search for Dennis.
[upload3.0.3.9.zip](https://github.com/MultiSafepay/opencart/files/13828645/upload3.0.3.9.zip)

**Comment by danielcivit** [comment]
Hi @dennisbuijsgmailcom 

Thanks for contacting us about this request. 

I have created a backlog item internally, to review and add support for PHP 8 and OpenCart 3.0.3.9.

I will keep you informed about progress on this as soon as we have progress.

**Comment by danielcivit** [comment]
Hi @dennisbuijsgmailcom 

Thanks for your comments and contributions.

We recently released a new version of the MultiSafepay OpenCart extension (v. 3.20.0) which now supports OpenCart 3.0.3.9 and PHP 8.X.

I am closing this issue at this moment, but feel free to reopen it if you have anything else to comment.
