### ISSUE TITLE
Using PayCharge extension will not redirect on checkout to Multisafepay 

### ISSUE THREAD

**Issue by dennisbuijsgmailcom** [MultiSafepay/Opencart#5]
Hi

Another issue that I couldn't find myself yet. I am using an extension https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=5040&filter_download_id=44&sort=price that adds another order total with name paycharge.
When paycharge apply and I press the payment button to goto Multisafepay, its loading and not redirected to Multisafepay but stay in the checkout page. Enabled logging but no error.

Best regards
Dennis

**Comment by dennisbuijsgmailcom** [comment]
When paycharge is not applied, the checkout is redirect normaly to the Multisafepay page.

**Comment by dennisbuijsgmailcom** [comment]
Hi

Problem is solved after investigation by Multisafepay, Paypal setup in my test Multisafepay envionment missing in combination with a pour error logging in Opencart extension not explaning the error.

Now its working on live website.
Thanks for the quick support.

Best regards
Dennis

**Comment by danielcivit** [comment]
Thank you @dennisbuijsgmailcom. 

We feel happy to assist you and improve our extension following your feedback and business case.

We continue taking care of the other issues opened by you, which remains open at this moment: https://github.com/MultiSafepay/opencart/issues/4, https://github.com/MultiSafepay/opencart/issues/7, https://github.com/MultiSafepay/opencart/issues/6
