### ISSUE TITLE
Opencart 4

### ISSUE THREAD

**Issue by LMG-Jeffy** [MultiSafepay/Opencart#9]
Will this module be available for Opencart 4 soon? Otherwise we make the choice to still use opencart 3 so that this module can be used.

Thanks in advance.

**Comment by danielcivit** [comment]
@LMG-Jeffy. Thanks for your interest. 

My apologies, somehow this message had been off our radar. 

Yes, we are working in a new extension for OpenCart 4, however we don't have a release date yet.

For sure we will back to this message as soon we start supporting the new OpenCart version, and share it with you. 

For the moment, our recommendation is continue using OC 3.X.X.X.
